### ISSUE TITLE
Configuration loader only loads configuration for users with home directories in /home

### ISSUE THREAD

**Issue by djmattyg007** [dshearer/jobber#11]
Currently the code that is responsible for loading the job configuration will only load configuration for with home directories in /home. This would prevent me from using this to run cron jobs as (for example) the webserver user, whose home directory is usually set to something like /srv/http or /var/www.

Instead of simply opening up every directory in /home (some of which may not even be home directories), wouldn't it be better to just parse /etc/users? This would also remove the need to handle the root user specially (the code for which is also kinda broken, as assuming /root is the root user's home directory is also not always a correct assumption).

**Comment by dshearer** [comment]
You're right.  I'll make that change.

Thank you for all the great suggestions, BTW!

**Comment by dshearer** [comment]
BTW, I presume you meant "parse /etc/passwd".

**Comment by dshearer** [comment]
Done!
