### ISSUE TITLE
Run jobber side by side with existing cron daemon

### ISSUE THREAD

**Issue by djmattyg007** [dshearer/jobber#12]
From what I can tell, this can run equally as well regardless of whether you have an existing cron daemon installed and running, and the two won't conflict with each other.

Is this true? If so, I feel like the documentation should be updated to reflect this. I think it would make it easier for people to try it out before committing to making the switch.

**Comment by dshearer** [comment]
Yes, it can run alongside cron.  And that's a good suggestion; I'll update the docs.

The only overlap with cron is that it logs to the syslog LOG_CRON facility.
