### ISSUE TITLE
Timezone for jobs

### ISSUE THREAD

**Issue by tdemco** [dshearer/jobber#15]
It would be useful if you could specify which timezone the 'time' field refers to.

So in the configuration you could add a field
 - Timezone: US/Eastern
If you need to specify which timezone it should run in, and by default if it is not defined, you could have it use the local time.

**Comment by dshearer** [comment]
Could you give an example where this would be useful?  I can't immediately see why you might want to use a timezone other than the host's local timezone.

**Comment by austinbutler** [comment]
What about a job that runs year-round and needs to be run at a certain time local to a region? DST may be used on the local server, but not in the remote location, or vice-versa.

**Comment by dshearer** [comment]
@austinbutler I'm sorry, I didn't notice your comment.  Would timezone support be useful for you?

**Comment by austinbutler** [comment]
It would, although at this point I ended up going with fcron instead because of that.

**Comment by dshearer** [comment]
I'll mark it "wontfix" for now, but let me know if you ever need it again.

**Comment by tolgaulas** [comment]
@dshearer would you reconsider this based on this sample use case. The machine that will run jobber need to call specific script on some specific times of different timezones (i.e sending a report when they started working in Rome office while the server is in Tokyo). So let say we can define multiple jobs with different timezones at each.
