### ISSUE TITLE
Pack as snap

### ISSUE THREAD

**Issue by techtonik** [dshearer/jobber#164]
I wonder it it is possible to install `jobber` as snap? snaps are containerized apps, so I don't know if they are allowed to run system service and invoke other services, but it is interesting to research the limitations.

https://tutorials.ubuntu.com/tutorial/basic-snap-usage#0
https://docs.snapcraft.io/build-snaps/go

**Comment by dshearer** [comment]
I’ll look into it.

**Comment by dshearer** [comment]
I took some time to play around with this.  Snaps certainly look convenient, but the problem is that they get restricted privileges, whereas Jobber must be able to do arbitrary things.  So it seems to me that snap won't work well for Jobber.
