### ISSUE TITLE
Runner proc won't start when jobfile has bad perms

### ISSUE THREAD

**Issue by techtonik** [dshearer/jobber#165]
Jobber doesn't work after installing 1.3.0 over 1.2.1 on Ubuntu 17.10.
```
# dpkg -i jobber_1.3.0-1_amd64_ubuntu16.deb
# jobber list
dial unix /var/jobber/0/cmd.sock: connect: connection refused
# ls -la /var/jobber/0/
total 12
drwxr-x--- 2 root root 4096 Jan 31 06:41 .
drwxr-xr-x 9 root root 4096 Jan 31 06:38 ..
srw------- 1 root root    0 Jan 31 06:41 cmd.sock
-rw------- 1 root root    3 Jan 31 06:41 runner_pid
```

**Comment by dshearer** [comment]
Could you check if there’s a daemon called “jobberrunner” running?

**Comment by zelenin** [comment]
Same error. Jobberruner is running.

**Comment by dshearer** [comment]
I see what's happening.  This is a design mistake on my part.  Jobber 1.3.0 is stricter about the permissions of the jobfile: it won't work if the 'group' or 'other' permission bits include w.  

There is also a real bug: jobberrunner process is supposed to run even if it won't load the jobfile, but instead it is crashing.

**Comment by dshearer** [comment]
The workaround is to set .jobber's perms to 0600.

**Comment by dshearer** [comment]
PR #166

**Comment by dshearer** [comment]
Symptom: `/var/jobber/0/cmd.sock: connect: connection refused`

**Comment by techtonik** [comment]
1.3.1 works. I had to remove write privilege from group after it started. Thanks.
