### ISSUE TITLE
jobberd exits with code 1

### ISSUE THREAD

**Issue by i0n** [dshearer/jobber#17]
Hey. I've tried compiling jobber with go 1.4.3 and go 1.5 on both Debian (wheezy) and OS X (10.11).

In every situation both binaries compile without error, the jobber client binary seems to work (can output help etc), but running jobberd always results in the process exiting with code 1 and no output.

Sorry I can't offer more help for debugging, but there is no error message.

**Comment by dshearer** [comment]
Thank you for letting me know. I'll look into it. 

Regards,
Dylan

**Comment by blacklabelops** [comment]
I have the same issue. Demon exits with code 1.

I am using:

* CentOS 7.1.503
* go version go1.4.2 linux/amd64

Build can be reproduced with this Dockerfile:
https://github.com/blacklabelops/jobber-cron/blob/master/Dockerfile

**Comment by dshearer** [comment]
I've made some changes to the code and the Makefile should fix this.

Please also use the changes to your Dockerfile in https://github.com/blacklabelops/jobber-cron/pull/2

**Comment by blacklabelops** [comment]
Solved for me.
