### ISSUE TITLE
When jobfiles are read, errors are silently disposed of

### ISSUE THREAD

**Issue by fuzzyami** [dshearer/jobber#19]
I accidentally created the .jobber file as root in my user's home dir. Jobber did not load the file (which is okay) but silently ignored it (not good). Consider adding a log or prints to stdout?

Thanks for this project! It just needs a REST API to make it perfect :]

**Comment by dshearer** [comment]
Would a REST API really be useful for you?

**Comment by fuzzyami** [comment]
it would have been at the time. I couldn't find something like this with a proper REST interface. The alternatives were either too big (like Chronos) or didn't have REST. anyways, that product has died since, so I dont need it anymore. thanks, though!

**Comment by fuzzyami** [comment]
it would have been at the time. I couldn't find something like this with a proper REST interface. The alternatives were either too big (like Chronos) or didn't have REST. anyways, that product has died since, so I dont need it anymore. thanks, though!

**Comment by dshearer** [comment]
[vagrant@localhost ~]$ sudo chown root ./.jobber
    [vagrant@localhost ~]$ jobber reload
    Failed to read jobfile /home/vagrant/.jobber: invalid argument

**Comment by dshearer** [comment]
Dup of #93
