### ISSUE TITLE
How to reference a resultSink in a job?

### ISSUE THREAD

**Issue by EugenMayer** [dshearer/jobber#194]
Could neither find it on the website nor in the wiki - any chance we could add that to the docs? Thanks!

**Comment by EugenMayer** [comment]
Was trying it this way, but i am really not sure how it is planned to be used https://github.com/EugenMayer/docker-cron-boilerplate/blob/master/jobber/crons/www-data.yml#L17

**Comment by dshearer** [comment]
This feature hasn't been released yet.  For now, if you want to write job output to disk, you can use a "notify program" (https://dshearer.github.io/jobber/doc/v1.3/#notifications).

**Comment by EugenMayer** [comment]
I see - looking forward to resultSinks then. Thanks for this project, very helpful!

**Comment by dshearer** [comment]
Thank you for the kind words!
