### ISSUE TITLE
Support "every X units" in time spec.

### ISSUE THREAD

**Issue by dshearer** [dshearer/jobber#2]
Like "*/2" for "every 2 units".

**Comment by sbstnp** [comment]
Any plans ti have this feature supported? Would love to give it a go but I really need 'every X units' functionality.

Thanks

**Comment by dshearer** [comment]
Sure!  I'll work on it in the next few weeks. 

Dylan

**Comment by sbstnp** [comment]
I might have something working today, but I'm a Go n00b so it will be ugly and sub-optimal.

**Comment by josenano** [comment]
Any updates on this one?

**Comment by dshearer** [comment]
No updates --- sorry.  I've been busy.  I'll try to make time for this.

**Comment by dshearer** [comment]
I've added support for expressions like "*/2", but not like "1,2,3/2" or "1-31/2" (yet).
