### ISSUE TITLE
Darwin platform support

### ISSUE THREAD

**Issue by LEI** [dshearer/jobber#202]
First of all while attempting to use jobber on macOS Sierra, I had to create [`common/su_cmd_darwin.go`](https://github.com/LEI/jobber/commit/64b09e7dbf6d356c50a1f87e4051d4c5a938eb61) for it to compile successfully (osx `man su` almost matches freebsd).

Then after some more fiddling I realised jobbermaster couldn't properly list users since Apple's `/etc/passwd` does not contain this information. It would require an alternative `listUsers` method for `GOOS=darwin`.

By the way you might be aware of this but Go [build constraints](https://golang.org/pkg/go/build/#hdr-Build_Constraints) are useful for cross-platform programs, maybe it's worth integrating in the build system (if not already?).

Are you planning to fully support this OS, or are there too many other corner cases?
I would gladly help however I can, may it be contributing or testing.

Also as addressed in #200, running rootless would be nice.

**Comment by LEI** [comment]
Just stumbled upon #67: if jobber can run on macOS after some modifications, one could package it with [Homebrew](https://brew.sh) and leverage its [services](https://github.com/Homebrew/homebrew-services) to daemonize the program. Almost all files installed with `brew` live under `/usr/local` to allow non-root execution.

**Comment by dshearer** [comment]
Okiedokie, I’ll look into it.

**Comment by LEI** [comment]
The most reliable way seems to be `dscl . list /Users | grep -v '^_'` which outputs something like:

```
daemon
Guest
User1
nobody
root
```

For now I added an alternative `listUsers` function in [`jobbermaster/users_darwin.go`](https://github.com/LEI/jobber/blob/platform-darwin/jobbermaster/users_darwin.go).

**Comment by johnson7788** [comment]
Hi  bigman
is it support Mac now?

**Comment by dshearer** [comment]
Not yet.  I'll add it in next release.

**Comment by dshearer** [comment]
Pr #220

**Comment by johnson7788** [comment]
Perfect job!

**Comment by dshearer** [comment]
Don't know why this is still open.  It was done in 1.4.
