### ISSUE TITLE
Can't install apk binary

### ISSUE THREAD

**Issue by YutoUrakami** [dshearer/jobber#217]
Hi.

I'm trying build minimum docker image to use jobber.
But can't install jobber with the following error messages.

```
(1/1) Installing jobber (1.3.4-r0)
Executing jobber-1.3.4-r0.post-install
 * service jobber added to runlevel sysinit
 * WARNING: jobber is already starting
ERROR: jobber-1.3.4-r0.post-install: script exited with error 1
```

Dockerfile is here.
https://gist.github.com/YutoUrakami/bef506e0303c9082ac99b198ff977f2f

What's wrong?

**Comment by dshearer** [comment]
Hi!

The post-install script does not work in Docker, so you need to add `--no-scripts` to the apk command:

```
apk add --no-scripts --allow-untrusted jobber-1.3.4-r0.apk
```

FYI, you may want to use an "official" Jobber image: https://hub.docker.com/r/dshearer/jobber/tags/
