### ISSUE TITLE
Jobber doesn't seem to be running for user

### ISSUE THREAD

**Issue by ibnishak** [dshearer/jobber#218]
OS: Antergos

I compiled jobber. Then installed daemonize. I started jobbermaster as

sudo daemonize -u *myuser* /usr/local/libexec/jobbermaster 

When I try  to issue `jobber init`, I get the following error message. 

(No socket at /var/jobber/1000/cmd.sock.): stat /var/jobber/1000/cmd.sock: no such file or directory

**Comment by dshearer** [comment]
jobbermaster is meant to run as root; it then spawns instances of jobberrunner for each user.

**Comment by ibnishak** [comment]
As I pointed out, I run daemonize as sudo

**Comment by dshearer** [comment]
Yes, must you're telling daemonize to run as _myuser_  (`-u myuser`).

**Comment by dshearer** [comment]
If you get rid of the `-u myuser` part it should work.

**Comment by ibnishak** [comment]
thank you. That worked. 

Great tool!!
