### ISSUE TITLE
Highlight minimal example on https://dshearer.github.io/jobber/

### ISSUE THREAD

**Issue by mcandre** [dshearer/jobber#219]
I see a smattering of different files, but it is not clear how to:

* Install jobber
* Configure jobber to launch at boot
* Configure a new job

**Comment by dshearer** [comment]
- https://dshearer.github.io/jobber/doc/v1.3/#deployment
- This depends on your OS.
- https://dshearer.github.io/jobber/doc/v1.3/#jobfile
