### ISSUE TITLE
Environment Variables for Jobs

### ISSUE THREAD

**Issue by blacklabelops** [dshearer/jobber#22]
How do I set environment variables for the Jobber demon? Put them inside .bashrc or where do I have to define them globally so all Jobs gets access?

I am currently preparing cron tasks for amazonws. Cli command example: aws s3 ls

The credentials are applied using environment variables, e.g. AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY. Now I need a good mechanism to pass all docker environment variables to the demon or in worst case the required ones.

What I don't want: I do not want to specify the required environment variables inside the Jobber config or inside scripts.

My current workaround:
Calling this inside the docker entrypoint works:
export >> /etc/profile.d/jobber.sh

**Comment by dshearer** [comment]
For now, the best thing to do is define the vars in a shell script and then source that script in your job.

I’ll work on an enhancement whereby jobber sources the user’s .bashrc when it runs a job.

Dylan

**Comment by dshearer** [comment]
I'm trying to think how best to do this.  As I reread your post, I now wonder whether sourcing .bashrc would work for you?  Are the env vars in any script at all, so that you can source them from a script that jobber calls?  I'm not very familiar with Docker... How are the env vars set?

**Comment by blacklabelops** [comment]
I am still thinking about this as my workaround is still working fine for me.

Let's summarize the Docker requirements:

* A Docker container can have an arbitrary amount of environment variables.
* Environment variables are defined during container instantiation. There is no way to know which parameter will be defined -> That why i just pipe all envs inside the script file.
* Environment variables are managed by Docker. Docker sets environment variables each time the command is invoked. Means envs are not static after startup. If you restart the container then the envs are set anew by Docker.
* There is no way to fix the shell: Envs may one time set for bash then in another context the container may be started with sh or something else.

My conclusion is:

* Docker envs should be available in all shells.
* Docker envs should be available for all users.

Summary:

* This is no real job for Jobber as I am now also handling with Docker CentOS images and Alpine images. I guess the Docker image has to handle it itself and make the Envs "as available as possible" without breaking/overwriting other Envs.

**Comment by dshearer** [comment]
Not an issue.

**Comment by darabos** [comment]
I have the same issue, and I will use a similar workaround. (I added `export > /root/.profile` to `CMD` in the Dockerfile.) But I would describe the situation differently: There are some environment variables defined for the `jobberd` process. (I can see them in `/proc/<jobberd>/environ`.) I would like to have these variables passed on to the processes started by Jobber.

Perhaps this is an unreasonable request, as it would raise a number of questions in a multi-user environment. But it makes sense in single-user environments, such as a container.

Anyway, thanks for Jobber, it is way more pleasurable to use than `cron`!

**Comment by dshearer** [comment]
Daniel,

As you alluded, Jobber was designed to work in a multiuser environment, like cron.  Each job belongs to a user, and is run as that user. That's why your workaround works. 

However, it seems that everyone but me runs Jobber in a Docker
container!  

There are a few options:

1) Don't export vars by default, but support an option to do so in a config file. 

2) Export vars by default and support an option to disable this. 

I don't like #2 because it is not backwards compatible (it may change the behavior of existing installations). 

Is #1 any more convenient for you than your workaround?  What are the disadvantages of the workaround?

Dylan

**Comment by darabos** [comment]
> Is #1 any more convenient for you than your workaround?  What are the disadvantages of the workaround?

I don't know. Seems good so far :). Maybe you could just mention this in the documentation somewhere. I would not have thought of it if I had not found this issue.

**Comment by dshearer** [comment]
I see. I'll do that. Thanks for the feedback!

**Comment by scythargon** [comment]
Hello! Has this ended up being mentioned somewhere in the docs eventually?

I'm also running jobber in docker and ended up doing this:

```
# First in shell:
export > env

# And then in jobber config:

jobs:
  TestJob:
    cmd: bash -c "cd /code/ && source ./env && ./manage.py count_users"
    time: 0 *
```

But I would prefer something less ugly:)

**Comment by lethargosapatheia** [comment]
> Not an issue.

The problem is that jobber itself runs something like `su -c 'jobber'`, which means it doesn't load the user's environment. This is the reason why it doesn't load the environmental variables, this isn't a container issue, this is related to how linux/bash works.
The solution would be to run it with a login shell, i.e. such as `such - -c 'jobber'`
