### ISSUE TITLE
Jobber Dependency Broken

### ISSUE THREAD

**Issue by blacklabelops** [dshearer/jobber#24]
All my latest builds with jobber tell me that the following dependency has moved:

package code.google.com/p/go.net/context: unable to detect version control system for code.google.com/ path
make: *** [build] Error 1

Full build log here:
https://circleci.com/gh/blacklabelops/jobber-cron/14

**Comment by dshearer** [comment]
Balls. 

I'm traveling today so I'll fix it tomorrow.

**Comment by dshearer** [comment]
Fixed in v1.0.1.
