### ISSUE TITLE
jobber refuses to load jobs due to odd logging file format issue

### ISSUE THREAD

**Issue by EugenMayer** [dshearer/jobber#240]
i suddently happen to notice that no jobber-jobs are running and also `jobber list` does not list any.

Searching for quiet a while a happen to notice that

`jobber reload`

fails with

`Call to Jobber failed: Invalid log file: /mnt/log/dwcore/cron-history: size is less than entry size`

This was a log file before, and even if i do 

`echo "" > /mnt/log/dwcore/cron-history` 

to flush the logfile, i get the same error message. Only if rm the file entirely, i can reload the jobs and let them run.

My jobs log config looks like this:
```
[prefs]
runLog:
  type: file
  path: /mnt/log/dwcore/cron-history
  maxFileLen: 100m
  maxHistories: 2
```

I am currently not even able to explain what this error message actually mean, but for sure it should not road-block running jobber if the log-file does have an "unexpected EOL" or even "a blank line" or whatever it might actually be

is that actually supposed to happen / is by design?

**Version**
tried 1.3.2 and 1.3.4

**Suggestion**
If that is by design, i would at least try to start a discussion if that makes sense.

I suggest, never fail to load or run jobs because of the logfile being missformatted, non existing or even like in this case ( i do not even no ) not being of the "right size"? Always load the jobs, always run them

**Workarround**
I could ensure this does not happen when remove the runLog configuration entirely, which i did

**Comment by EugenMayer** [comment]
Any chance we could move this forward? I found out that the reason for this was a copy&paste issue for 2 jobber configurations sharing the same log-path.

I understand that this is a configuration issue, but beside that really can happen, the second point is, that clearing the log ( `echo "" > logfile` ) makes the file broken too.

I would really love to have this just a little more robust / warning alike. Any chance of a discussion about this?

**Comment by dshearer** [comment]
Yeah. I’ll look into it this weekend.

**Comment by EugenMayer** [comment]
@dshearer thank you a lot, let me know if you need anything

**Comment by dshearer** [comment]
I agree with your suggestion.  Unfortunately I'm sick, so I may not make much progress this weekend.

**Comment by EugenMayer** [comment]
No worries, i wish you to get better soon.

**Comment by dshearer** [comment]
The doctors resuscitated me just so I could work on this bug.

**Comment by EugenMayer** [comment]
Back from the dead - that is real bad ass :)
I guess sqaushing bugs won't be a challenge any longer. Thanks for taking your time for that one!

**Comment by EugenMayer** [comment]
I guess this one died? :)

**Comment by dshearer** [comment]
Lol... Sorry. I’ll get to it.
