### ISSUE TITLE
Add build for alpine > 3.6

### ISSUE THREAD

**Issue by pagameba** [dshearer/jobber#254]
Hi, would like to use your excellent looking tool on alpine linux 3.8/3.9.  It appears that the `service` command used to start jobber has been renamed to `rc-service` somewhere along the way.  By way of a work-around, I've forked it and attempted to make newer alpine build target but haven't got it to work yet (I'm building it in a multi-stage Dockerfile rather than vagrant).

**Comment by dshearer** [comment]
I think we do support the latest Alpine versions.
