### ISSUE TITLE
stuck on yaml with install

### ISSUE THREAD

**Issue by yosefy** [dshearer/jobber#26]
[root@ansible gospace]# go get -v gopkg.in/yaml.v2 
Fetching https://gopkg.in/yaml.v2?go-get=1
Parsing meta tags from https://gopkg.in/yaml.v2?go-get=1 (status code 200)
get "gopkg.in/yaml.v2": found meta tag main.metaImport{Prefix:"gopkg.in/yaml.v2", VCS:"git",
 RepoRoot:"https://gopkg.in/yaml.v2"} at https://gopkg.in/yaml.v2?go-get=1
gopkg.in/yaml.v2 (download)

and waiting forever...
cant install

**Comment by dshearer** [comment]
Sorry about that.  I just released v1.0.2 in which all dependencies are vendored in the Jobber repo (using Godep). So, in your Jobber repo clone, please do 'git checkout v1.0.2' and then 'make'.  You shouldn't have a problem.
