### ISSUE TITLE
Packaging: Debian package for armhf/Raspbian?

### ISSUE THREAD

**Issue by jjorissen52** [dshearer/jobber#260]
First I want to say jobber is amazing. Using `jobber test JOBNAME` saved me from potentially hours of debugging a tricky cronjob setup, and was well worth taking the time to install it on Raspberry Pi. With that in mind, I plan to use it a lot more in the future... Is it possible to add a .deb release for arm CPU architecture? I don't really know what packaging it entails but I'd be happy to take a crack at it.

**Comment by dshearer** [comment]
Thank you for the kind words. Unfortunately, I'm moving to GitHub Actions and it doesn't support ARM just yet.

**Comment by jjorissen52** [comment]
Well, if there's no interest then I understand and I'll leave it at that. However, though a bit ugly (and apparently slow), it seems one can build and test for many architectures using qemu emulation. Here's a GitHub repo that does so https://github.com/zhangyoufu/alpine
