### ISSUE TITLE
Jobber Binaries Release

### ISSUE THREAD

**Issue by blacklabelops** [dshearer/jobber#27]
I am currently pursuing minimal Docker images. Is it possible that you can release binaries? This way I don't have to install the toolset for compiling the sources.

I am using amd64 platform.

**Comment by dshearer** [comment]
In fact, I've been thinking about making binary distros.  What package manager do you use?

**Comment by blacklabelops** [comment]
I am using:

* apk on Alpine
* yum on CentOS

**Comment by blacklabelops** [comment]
I am quite fine with the binaries for jobber and jobberd already. I am pretty confident with the installation routine by now.

**Comment by blacklabelops** [comment]
It is mandatory that I am able to install a fix version! Can you tell me how to build binaries from sources that would solve my issue!

Please take a look at my two installation routines inside my Dockerfile: https://github.com/blacklabelops/jobber-cron/blob/alpine/Dockerfile

Because `go get` does not support any versioning I wall always get the latest master sources. Now I download the sources of a specific release and want to compile it.

I get the following:
make: Entering directory '/tmp/jobber'
bash update-version.sh
fatal: Not a git repository (or any of the parent directories): .git
go install github.com/dshearer/jobber
can't load package: package github.com/dshearer/jobber: cannot find package "github.com/dshearer/jobber" in any of:
	/usr/lib/go/src/github.com/dshearer/jobber (from $GOROOT)
	/tmp/jobber/lib/src/github.com/dshearer/jobber (from $GOPATH)
make: *** [build] Error 1
cp: can't stat '/tmp/jobber/lib/bin/*': No such file or directory
Makefile:21: recipe for target 'build' failed 

What would you propose? Would `git clone` on a release tag solve the issue?

**Comment by blacklabelops** [comment]
Only for you! A Docker build building a binary Jobber release: https://github.com/blacklabelops/jobber-cron/tree/alpine/jobber-build

Maybe it's a valid idea to build a binary distribution and then adapt an installer without the whole build procedure?

**Comment by dshearer** [comment]
I'll work on scripts that make a binary package for Alpine.

**Comment by blacklabelops** [comment]
Looks like there is some fine progress! Is there a release date and where can I download them?

**Comment by dshearer** [comment]
I'm slowwwly making progress...  I'm now building RPMs... which is not what you want!  But I can use the same structure for the Alpine builds.  I'll need another week or so.

**Comment by blacklabelops** [comment]
In essence I want to be able to build a docker image from a release not only from master.

Either from:
- A downloadable package.
- Downloadable Source
- Binaries

Maybe one of those is already working for Alpine?

**Comment by dshearer** [comment]
I have FINALLY finished this!  An Alpine package is available on the releases page, under v1.0.3.2.

If you want, you can also build the package yourself.  On an Alpine host, checkout the sources, then cd into packaging/alpine_3.3/ and do "make pkg-local".

Let me know if this meets your needs.

**Comment by blacklabelops** [comment]
Thanks for the binaries. I included an installation routine but have problems with some dependencies.

I tried to install them inside a Docker image, I get the following error message:

Install Command:
```
wget --directory-prefix=/tmp https://github.com/dshearer/jobber/releases/download/v1.1/jobber-${JOBBER_VERSION}-r0.x86_64.apk && \
apk add --allow-untrusted /tmp/jobber-${JOBBER_VERSION}-r0.x86_64.apk
```

Message:

```
(1/1) Installing jobber (1.1-r0)
Executing jobber-1.1-r0.post-install
**** WARNING ****
We are installing a non-PIE SUID-root program
(namely, /usr/bin/jobber).  It seems that
Alpine's developers dislike this, with reason.
When Go supports PIEs, we'll fix this.
*****************
var/cache/misc/jobber-1.1-r0.post-install: line 24: rc-update: not found
var/cache/misc/jobber-1.1-r0.post-install: line 25: service: not found
ERROR: jobber-1.1-r0.post-install: script exited with error 127

```

**Comment by dshearer** [comment]
What does your docker file look like?

**Comment by blacklabelops** [comment]
Dockerfile is here: https://github.com/blacklabelops/jobber-cron/blob/master/Dockerfile

**Comment by dshearer** [comment]
I haven't had time to mess with your dockerfile yet. I see you're still making the jobber user. The package takes care of all that now.

**Comment by dshearer** [comment]
This is the dockerfile I use to test the package: https://github.com/dshearer/jobber/blob/master/platform_tests/alpine_3.3/Dockerfile

**Comment by blacklabelops** [comment]
What's inside your PKG_DIR=/pkgs?

**Comment by dshearer** [comment]
The apk file.

**Comment by blacklabelops** [comment]
I have modified your Dockerfile with a downloading routine: [Dockerfile](https://github.com/blacklabelops/jobber-cron/blob/apktest/DockerfileJobber)

I still get the same error:

~~~
(1/1) Installing jobber (1.1-r0)
Executing jobber-1.1-r0.post-install
**** WARNING ****
We are installing a non-PIE SUID-root program
(namely, /usr/bin/jobber).  It seems that
Alpine's developers dislike this, with reason.
When Go supports PIEs, we'll fix this.
*****************
var/cache/misc/jobber-1.1-r0.post-install: line 24: rc-update: not found
var/cache/misc/jobber-1.1-r0.post-install: line 25: service: not found
ERROR: jobber-1.1-r0.post-install: script exited with error 127
~~~

**Comment by dshearer** [comment]
Those errors are because the package assumes that rc-init is installed.  jobber should still have been installed successfully though.

**Comment by dshearer** [comment]
Does it seem to be working?

**Comment by blacklabelops** [comment]
Currently, I am fine with checking out the tags and build the version myself. This way I do not have to ignore installation errors and be aware of any build problems.
