### ISSUE TITLE
Aarch64 Compatible Jobber APK

### ISSUE THREAD

**Issue by odidev** [dshearer/jobber#273]
Hi Team, 

I am not able to find apk for aarch64 in its release. Is there any plan to release aarch64 compatible jobber apk.

**Comment by odidev** [comment]
Ping @dshearer could you please share your thoughts on this.

**Comment by dshearer** [comment]
Let me look into it this weekend.

**Comment by odidev** [comment]
Thanks @dshearer Please let me know if you have any suggestions.

**Comment by odidev** [comment]
@dshearer did you get the time to look at the issue?

**Comment by odidev** [comment]
Ping @dshearer could you please share your thoughts on this.

**Comment by dshearer** [comment]
I’m trying to finish up making a Homebrew package for Jobber.  I’ll get to your task next.

**Comment by odidev** [comment]
Hi @dshearer, sure thanks for the response.

Can we add support for arm64 apk build in Travis-Ci so that we could obtain the apk binary from the Travis or are there any other methods to generate the apk binary for arm64?

**Comment by odidev** [comment]
Ping @dshearer could you please share your thoughts on this.

**Comment by rhenwood-arm** [comment]
@odidev can you provide a PR to do an AArch64 APK build using Travis-CI?

**Comment by dshearer** [comment]
I’ll look into this this weekend. I’d like to move toward using GitHub to do the builds rather than Travis or Circle.

**Comment by dshearer** [comment]
Looks like GitHub Actions does not support ARM (unless we use self-hosted runners). As I said, I want to stick with GitHub Actions from now on.  Sorry.

**Comment by odidev** [comment]
@dshearer, 

As per our [previous conversation](https://github.com/dshearer/jobber/issues/273#issuecomment-633733336) I had tried to build this package for ARM64 in **Github Action** using qemu and was able to build and release the [binaries ](https://github.com/odidev/jobber/releases/download/1.4.4/jobber-1.4.4-arm64-r0.apk)for arm64 by implementing [these ](https://github.com/odidev/jobber/commit/ede10c7efcd8295150dce27f1fda8d9aa6b606d7)changes.

**ARM64 Binary:** https://github.com/odidev/jobber/releases/download/1.4.4/jobber-1.4.4-arm64-r0.apk

**Changes required:**  https://github.com/odidev/jobber/commit/ede10c7efcd8295150dce27f1fda8d9aa6b606d7

Do you have any plans for releasing an ARM64 Binaries?

May I know how the amd64 binaries are getting released?

If interested, I will raise a PR.
