### ISSUE TITLE
Jobber Installer Not Working On Alpine

### ISSUE THREAD

**Issue by blacklabelops** [dshearer/jobber#28]
The installer is not working on Alpine because the instructions to add and remove users are different:

Log:
make: Entering directory '/opt/jobber/lib/src/github.com/dshearer/jobber'
bash update-version.sh
go install github.com/dshearer/jobber
go install github.com/dshearer/jobber/jobber
go install github.com/dshearer/jobber/jobberd
TMPDIR="/opt/jobber/lib" go test github.com/dshearer/jobber/jobberd
ok  	github.com/dshearer/jobber/jobberd	2.678s
userdel jobber_client
Makefile:50: recipe for target '/opt/jobber/bin/jobber' failed
useradd --home / -M --system --shell /sbin/nologin "jobber_client"
make: userdel: Command not found
make: [/opt/jobber/bin/jobber] Error 127 (ignored)
/bin/sh: useradd: not found
make: *** [/opt/jobber/bin/jobber] Error 127
Makefile:50: recipe for target '/opt/jobber/bin/jobber' failed
make: Leaving directory '/opt/jobber/lib/src/github.com/dshearer/jobber'

Working command example for Alpine:
adduser -u 1000 -G jenkins -h /usr/bin/logrotate.d -s /bin/bash -S jenkins

**Comment by dshearer** [comment]
I'll work on this.

**Comment by blacklabelops** [comment]
I really appreciate your effort! Alpine helps me to decrease the image size of any Docker image by nearly 300MB!

**Comment by dshearer** [comment]
I'm now building Alpine packages, so this isn't any issue anymore.
