### ISSUE TITLE
Jobber Job Execution Does Not Work On Alpine

### ISSUE THREAD

**Issue by blacklabelops** [dshearer/jobber#29]
When I execute a job then Jobber cant execute because of unknown option in command su in Alpine:

Looks like Jobber build an execution command that does not work with the su inside this distribution. Is there a workaround or does it have to be adjusted?

Log:
bash-4.3# jobber list
NAME     STATUS  SEC/MIN/HR/MDAY/MTH/WDAY  NEXT RUN TIME         NOTIFY ON ERR  NOTIFY ON FAIL  ERR HANDLER
Hourly   Good    0 20 */4 * * *            Feb 17 16:20:00 2016  false          false           Continue
Daily    Good    0 30 1 * * *              Feb 18 01:30:00 2016  false          false           Continue
Weekly   Good    0 40 2 * * 5              Feb 19 02:40:00 2016  false          false           Continue
Monthly  Good    0 50 4 1 * *              Mar  1 04:50:00 2016  false          false           Continue
bash-4.3# jobber test Hourly
Running job "Hourly" for user "root"...
Job "Hourly" failed.
New status: Good.

Stdout:

Stderr:
su: unrecognized option: login
BusyBox v1.24.1 (2015-12-16 08:00:02 GMT) multi-call binary.

Usage: su [OPTIONS] [-] [USER]

Run shell under USER (by default, root)

	-,-l	Clear environment, run shell as login shell
	-p,-m	Do not set new $HOME, $SHELL, $USER, $LOGNAME
	-c CMD	Command to pass to 'sh -c'
	-s SH	Shell to use instead of user's default

bash-4.3# su --help
BusyBox v1.24.1 (2015-12-16 08:00:02 GMT) multi-call binary.

Usage: su [OPTIONS] [-] [USER]

Run shell under USER (by default, root)

	-,-l	Clear environment, run shell as login shell
	-p,-m	Do not set new $HOME, $SHELL, $USER, $LOGNAME
	-c CMD	Command to pass to 'sh -c'
	-s SH	Shell to use instead of user's default

**Comment by dshearer** [comment]
Fixed in 77173f883c5fc0db0c9ee56d02496555b2106ea9.

**Comment by blacklabelops** [comment]
Thanks! I now have a working blacklabelops/jobber-cron:alpine Docker image with the size of 27.43 MB. This makes jobber the perfect solution for cron inside Docker!
