### ISSUE TITLE
Mail Notifications Inside Docker

### ISSUE THREAD

**Issue by blacklabelops** [dshearer/jobber#31]
Docker best-practise is a single-process approach inside an Image. I have no mail demon running inside my Jobber Image ([blacklabelops/jobber](https://hub.docker.com/r/blacklabelops/jobber/)). Jobber's included mail notification does not work.

My use-case:

1. Job fails.
1. Notification is send using smtp.sendgrid.com server with a custom username and password
1. Advanced: Secured TLS enabled smtp.sendgrid.com with server certificate

Example Docker Environment Parameters:
-e "SMTP_USER_NAME=mypersonaluser" \
-e "SMTP_USER_PASS=swordfish" \
-e "SMTP_HOST=smtp.sendgrid.com" \
-e "SMTP_PORT=587" \

I need either a command line tool that does not need a local demon, can be configured by the settings above or direct Jobber support (E.g. Mail API and appropriate configuration part.)

**Comment by dshearer** [comment]
How about this: In the jobber file, you can specify a script.  When a job fails, jobber will call that script and pass on stdin a json document like this: {"status": "Failed", "stdout": "...", "stderr": "..."}.  That script can do what it wants.
