### ISSUE TITLE
FreeBSD err

### ISSUE THREAD

**Issue by Caes95** [dshearer/jobber#33]
carlos@src:~ % jobber test "Clear logs"
Running job "Clear logs" for user "carlos"...
Job "Clear logs" failed.
New status: Good.

Stdout:

Stderr:
su: unknown login: /bin/sh

------
carlos@src:~ % cat .jobber
---
- name: Clear
  cmd: |
    cd /usr/game/
  time: "0 0 */3 * * *"
  onError: Stop
  notifyOnError: true
  notifyOnFailure: true

**Comment by dshearer** [comment]
Roger.

**Comment by dshearer** [comment]
FreeBSD support has been addd in version 1.1.
