### ISSUE TITLE
Make Debian releases

### ISSUE THREAD

**Issue by darabos** [dshearer/jobber#41]
It is not too hard to build Jobber from source, but `.deb` releases would be nice. Thanks!

(The build instructions for Debian are at https://github.com/dshearer/jobber/blob/v1.1/DEBIAN_UBUNTU.md.)

**Comment by dshearer** [comment]
Roger.

**Comment by stephane-martin** [comment]
you can try https://github.com/jordansissel/fpm to make the packages, that would be trivial to make a deb package for just the binaries

**Comment by stephane-martin** [comment]
(and please don't forget to include a service file for systemd ;))

**Comment by dshearer** [comment]
Thanks for the suggestion!  I hadn't heard of FPM.

**Comment by dshearer** [comment]
Done!  You can get it here: https://github.com/dshearer/jobber/releases/tag/v1.1
