### ISSUE TITLE
Not able to start on RedHat 7

### ISSUE THREAD

**Issue by zsustar** [dshearer/jobber#46]
Hi 

i have two instances on AWS one is RH6 and another is RH7. 
jobber working perfectly on RH6 but failed on RH7, could anyone please have a check? thanks!

Error Output:
$systemctl status jobber.service -l
● jobber.service - LSB: jobber
   Loaded: loaded (/etc/rc.d/init.d/jobber)
   Active: failed (Result: exit-code) since Wed 2016-08-03 01:42:55 EDT; 24s ago
     Docs: man:systemd-sysv-generator(8)

Aug 03 01:42:55 systemd[1]: Starting LSB: jobber...
Aug 03 01:42:55 systemd[1]: jobber.service: control process exited, code=exited status=203
Aug 03 01:42:55 systemd[1]: Failed to start LSB: jobber.
Aug 03 01:42:55 systemd[1]: Unit jobber.service entered failed state.
Aug 03 01:42:55 systemd[1]: jobber.service failed.

**Comment by dshearer** [comment]
Looks like jobber's init script isn't working well with systemd. How did you install Jobber?  Did you use the rpm?

Dylan

**Comment by zsustar** [comment]
hi Dylan,

Yes I used rpm to install the RPM downloaded from here.

One more thing, the system asked for daemonize as it's the dependency to install jobber rpm.
So i downloaded the daemonzie rpm from following website
https://www.rpmfind.net/linux/rpm2html/search.php?query=daemonize
(Sorry i don't know how to compile the source code, so have to download the rpm somewhere...)

I executed following commands to download and install the daemonzie and jobber rpm file:
# wget ftp://195.220.108.108/linux/fedora/linux/releases/                                 24/Everything/x86_64/os/Packages/d/daemonize-1.7.7-2.fc24.x86_64.rpm

#wget https://github.com/dshearer/jobber/releases/download/v1.1/jobber-1.1-1.x86_64.rpm

#sudo rpm -ivh daemonize-1.7.7-2.fc24.x86_64.rpm jobber-1.1-1.x86_64.rpm
warning: daemonize-1.7.7-2.fc24.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 81b46521: NOKEY
Preparing...                          ################################# [100%]
Updating / installing...
   1:daemonize-1.7.7-2.fc24           ################################# [ 50%]
   2:jobber-1.1-1                     ################################# [100%]
Reloading systemd:                                         [  OK  ]
Starting jobber (via systemctl):  Job for jobber.service failed because the control process exited with error code. See "systemctl status jobber.service" and "journalctl -xe" for details.
                                                           [FAILED]

**Comment by Shamunr** [comment]
I believe this issue can be fixed by simply adding the following to the top of /etc/rc.d/init.d/jobber  :  

#!/bin/sh -

Doing that it works for CentOS 7 for me using systemctl / systemd

**Comment by dshearer** [comment]
Sorry @zsustar, I got distracted...  Did @Shamunr's suggestion work?

**Comment by zsustar** [comment]
@Shamunr @dshearer , still not working...
$sudo systemctl status jobber.service -l
● jobber.service - LSB: jobber
   Loaded: loaded (/etc/rc.d/init.d/jobber)
   Active: failed (Result: exit-code) since Wed 2016-08-03 15:49:52 AEST; 2 weeks 4 days ago
     Docs: man:systemd-sysv-generator(8)
  Process: 29934 ExecStart=/etc/rc.d/init.d/jobber start (code=exited, status=203/EXEC)
Warning: jobber.service changed on disk. Run 'systemctl daemon-reload' to reload units.

==================
sudo more  /etc/rc.d/init.d/jobber
#!/bin/sh
### BEGIN INIT INFO

**Comment by Shamunr** [comment]
@zsustar 
Run the command it gives: systemctl daemon-reload

Also please keep in mind you also require the - at the end.  Copy paste:
#!/bin/sh -

**Comment by dshearer** [comment]
I think I need to make a package that supports systemd. I'll get one out in the next few days. 

Dylan

**Comment by Tfindelkind** [comment]
can't await the systemd support. Would like to use jobber in my project which is based on Ubuntu 14.04 and Centos 7. Got the same problem. #!/bin/sh - did not help.

**Comment by dshearer** [comment]
@zsustar, @Tfindelkind: Sorry for the delay.  I've made a CentOS 7 package that should work on RHEL 7.  https://github.com/dshearer/jobber/releases/tag/v1.1

@Tfindelkind: There's already a Debian 8.5 package.  It should work, I think.

**Comment by Tfindelkind** [comment]
thanks. tested with Centos7. works

**Comment by zsustar** [comment]
sorry for late response. it's working on RH 7 now.  
Thanks!!
