### ISSUE TITLE
Support for random execution?

### ISSUE THREAD

**Issue by rmenessec** [dshearer/jobber#50]
It would be great to see support for periodic jobs with random delays and random intervals.

Thanks!

**Comment by binary64** [comment]
I have some flesh for this idea:-

I plan on having many instances of jobber running in a docker swarm, all with the same timing config. This leads to an issue for my hourly cron where multiple containers will all work at the same millisecond. I would like to specify something like this for the interval:

`? * * * * *`

where the ? means "Select a random value within the range (0-59 in this case), and stick with it!" so for example on init it would choose 35 let's say.. so every ::35 it will now execute.

The hourly cron could perhaps be:

`? ?2-10`

Which for example means "Execute every *:07:33"

Many thanks!

**Comment by dshearer** [comment]
Thanks for the suggestion!  Since it seems there are at least two people interested in this feature, I’ll make it more of a priority.

Regards,
Dylan

**Comment by binary64** [comment]
Jenkins just suggested this to me, I wonder if `H` is already supported. Or if not, to use that syntax instead of my `?` idea.

`Spread load evenly by using ‘H 1 * * *’ rather than ‘0 1 * * *’`

**Comment by dshearer** [comment]
PR #136

**Comment by techtonik** [comment]
So the syntax is `0 0 R5-8` etc. which makes it incompatible with `cron`, because `cron` doesn't support this feature without some nasty hacks - https://stackoverflow.com/questions/9049460/cron-jobs-and-random-times-within-given-hours

**Comment by dshearer** [comment]
Sure. I’m adding a feature that cron doesn’t support, so time specs that use that feature won’t be compatible with cron.
