### ISSUE TITLE
Fires off job multiple times until crash 

### ISSUE THREAD

**Issue by saitoh183** [dshearer/jobber#57]
Hi, here is my jobber script:

```
---
- name: PlexEmail
  cmd: /usr/bin/python /opt/plexEmail/scripts/plexEmail.py -t
  time: "* 51 13 * * *"
  onError: Stop
  notifyOnError: false
  notifyOnFailure: false
```

When i use the test command, it does the job and stops right after and i receive my email. But when the task is triggered from the schedule, It is as if jobber launches the task like 30+ times which results in me getting 30+ emails of the same thing till the task crashes because of out of memory. I dont understand why it doesnt do like when i run the test

**Comment by dshearer** [comment]
The first "*" in the time spec means "any second".  So the job will run whenever the current minute is 51, the current hour is 13, and the current second is anything.  So it'll run 60 times at 1:51 PM.

Change it to "0 51 13 * * *".

**Comment by saitoh183** [comment]
Thank you sir...Love this program!
