### ISSUE TITLE
Allow run history to be kept or purged according to config

### ISSUE THREAD

**Issue by dshearer** [dshearer/jobber#6]
How long should run history be kept?
How should users be able to purge it?

**Comment by trixtur** [comment]
I think /var/log/ logs get rotated regularly. If not, one could create a jobber task to do it ;-)

Perhaps dumping the run-log out to a log file and purging the log would work.

**Comment by trixtur** [comment]
I did some quick research. It doesn't appear to be Jobber's responsibility to purge its run history. It would be good to communicate to users that they should have logrotate and configure logrotate.d for jobber.

**Comment by trixtur** [comment]
There is a problem with the method I'm using. In the split second between dumping the runLog from memory and restarting the daemon, we could have jobs run and we lose logs.

Honestly the best way to go is to write directly to the filesystem the way jobber used to and then use logrotate to compress the logs.

**Comment by dshearer** [comment]
Thanks for the feedback --- I'll do something about this.

**Comment by trixtur** [comment]
May I suggest logging to a database table?

**Comment by dshearer** [comment]
Good idea.

**Comment by dshearer** [comment]
PR #100

**Comment by techtonik** [comment]
To `journalctl`?

**Comment by dshearer** [comment]
Currently, it can just write the log to an arbitrary file.  (It does rotation itself.)
