### ISSUE TITLE
Job always failing but runs when i do Test

### ISSUE THREAD

**Issue by saitoh183** [dshearer/jobber#60]
I have a job set for every 10 mins. But it always fails. If i run jobber test Filebot, the Job runs. I dont see any error in the log

```
NAME     STATUS  SEC/MIN/HR/MDAY/MTH/WDAY  NEXT RUN TIME         NOTIFY ON ERR  NOTIFY ON FAIL  ERR HANDLER
Filebot  Failed  0 */10 * * * *            Oct  2 22:40:00 2016  false          false           Stop
```

```

---
- name: Filebot
  cmd: /mnt/sde1/Scripts/Filebot/MediaMgmt.sh
  time: "0 */10 * * * *"
  onError: Stop
  notifyOnError: false
  notifyOnFailure: false
```

run with 

`sudo -H -u svc-saitoh bash -c 'jobber test Filebot'`

**Comment by dshearer** [comment]
That's frustrating.  Jobber will think it failed if it exists with non-0.  Is there any case where MediaMgmt.sh would exit with non-0 but not write any error msg?

**Comment by saitoh183** [comment]
Well maybe if there is a error moving a file but the Fail happens even if there is nothing to move.

This is the Filebot log when there is nothing in the folder to move

```
Run script [fn:amc] at [Sun Oct 02 22:23:41 EDT 2016]
No files selected for processing
```

But with or without files to process , it says failed.

Here is a test with the folders empty

```
saitoh183@SRV-SAITOH-APP:~$ sudo -H -u svc-saitoh bash -c 'jobber test Filebot'
[sudo] password for saitoh183: 
Running job "Filebot" for user "svc-saitoh"...
Job "Filebot" failed.
New status: Failed.

Stdout:
Locking /mnt/sdc2/Filebot.log
Run script [fn:amc] at [Sun Oct 02 22:55:03 EDT 2016]
Locking /mnt/sdc2/Filebot.log
Run script [fn:amc] at [Sun Oct 02 22:55:06 EDT 2016]


Stderr:
No files selected for processing
No files selected for processing
```

**Comment by saitoh183** [comment]
here is the jobber.err.log entry

`sudo: exit status 1`

**Comment by dshearer** [comment]
So that log ("exit status 1") explains why the job failed.  So it looks like MediaMgmt.sh exits with 1 when there are no files to move.  

What does a test with files to move look like?

**Comment by saitoh183** [comment]
testing now...wont be long

**Comment by saitoh183** [comment]
Sorry for the wait...had a issue with my script

With files moved, it still gets

sudo: exit status 1

**Comment by saitoh183** [comment]
ok...i noticed that the move some files were moved and some failed. So the return was 1...i think i have a issue with files that it is trying to move. Im going to try to find a file that is working

**Comment by saitoh183** [comment]
Ok..yeah even when the tasked succeeds i get a exit code of 1

Filebot log

```
Run script [fn:amc] at [Mon Oct 03 11:00:05 EDT 2016]
Rename movies using [TheMovieDB]
Auto-detect movie from context: [/mnt/sde1/Downloads_area/Feral/cpsfr/Warcraft.2016.MULTI.TRUEFRENCH.720p.BluRay.x264.AC3-ShowFr.mkv]
[MOVE] Rename [/mnt/sde1/Downloads_area/Feral/cpsfr/Warcraft.2016.MULTI.TRUEFRENCH.720p.BluRay.x264.AC3-ShowFr.mkv] to [/media/videos/Dual Audio Movies/Warcraft (2016)/Warcraft (2016).mkv]
Processed 1 files
Clean clutter files and empty folders
Run script [fn:amc] at [Mon Oct 03 11:04:57 EDT 2016]
No files selected for processing
```

Here is my script:

```
#!/bin/bash

filebot -script  fn:amc --def movieFormat="/media/videos/{audio.size() > 1 ? 'Dual Audio Movies' : 'French movies'}/{plex[1..-1]}" --action Move -non-strict /mnt/sde1/Downloads_area/Feral/cpsfr --log-file /mnt/sdc2/Filebot.log --def clean=y --def ut_label=movie -no-xattr --log Fine

filebot -script  fn:amc --def movieFormat="/media/videos/UFC/{plex[1..-1]}" --action Move -non-strict /mnt/sde1/Downloads_area/Feral/UFC --log-file /mnt/sdc2/Filebot.log --def clean=y --def ut_label=movie -no-xattr --log Fine

```

I wonder if it is the script part of my script that is making it exit with code 1 since there is nothing to proccess in the UFC folder. 

I will comment it out and try again.

**Comment by saitoh183** [comment]
nope even with the comment out of the non used portion, i still get a exit 1.

So test works but the schedule fails.

**Comment by dshearer** [comment]
Add "exit 0" at the very end of the script.

**Comment by dshearer** [comment]
Are you still having trouble with this?
