### ISSUE TITLE
Crashes due to memory exhaustion when there is plenty available

### ISSUE THREAD

**Issue by Shamunr** [dshearer/jobber#61]
The OS: CentOS 7 64 bit
Memory installed: 32g

The bug:  Jobberd crashes occasionally on my servers.  If I run "jobber status" I get: 

```
Couldn't connect to daemon: dial unix /var/jobber_daemon.sock: connect: connection refused
```

After running a "systemctl start jobber" (since its shown as dead) I get this:  
    Starting jobber (via systemctl):  Job for jobber.service failed because the control process exited with error code. See "systemctl status jobber.service" and "journalctl -xe" for details.

Then obviously doing that command I get this:  

```
● jobber.service - LSB: jobber
   Loaded: loaded (/etc/rc.d/init.d/jobber)
   Active: failed (Result: exit-code) since Tue 2016-10-11 01:19:47 EDT; 10s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 12236 ExecStop=/etc/rc.d/init.d/jobber stop (code=exited, status=0/SUCCESS)
  Process: 12233 ExecStart=/etc/rc.d/init.d/jobber start (code=exited, status=1/FAILURE)

Oct 11 01:19:47 localhost.localdomain systemd[1]: Starting LSB: jobber...
Oct 11 01:19:47 localhost.localdomain jobber[12233]: Starting jobberd: /bin/bash: fork: Cannot allocate memory
Oct 11 01:19:47 localhost.localdomain jobber[12233]: [FAILED]
Oct 11 01:19:47 localhost.localdomain systemd[1]: jobber.service: control process exited, code=exited status=1
Oct 11 01:19:47 localhost.localdomain systemd[1]: Failed to start LSB: jobber.
Oct 11 01:19:47 localhost.localdomain systemd[1]: Unit jobber.service entered failed state.
Oct 11 01:19:47 localhost.localdomain systemd[1]: jobber.service failed.
```

There is no issue with memory as running `free -g` returns:  

```
          total        used        free      shared  buff/cache   available
Mem:             31           9          17           0           4          17
Swap:             7           0           7
```

Doing a stop, restart, stop and then start I get this:  

```
● jobber.service - LSB: jobber
   Loaded: loaded (/etc/rc.d/init.d/jobber)
   Active: active (exited) since Tue 2016-10-11 01:21:14 EDT; 4s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 12236 ExecStop=/etc/rc.d/init.d/jobber stop (code=exited, status=0/SUCCESS)
  Process: 1850 ExecStart=/etc/rc.d/init.d/jobber start (code=exited, status=0/SUCCESS)

Oct 11 01:21:14 localhost.localdomain systemd[1]: Starting LSB: jobber...
Oct 11 01:21:14 localhost.localdomain systemd[1]: Started LSB: jobber.
```

Then doing `jobber status` :  

```
jobberd isn't running.
```

After doing some more stop and starts, I manage to get it to fail when doing `jobber` :  

```
runtime/cgo: pthread_create failed: Resource temporarily unavailable
SIGABRT: abort
PC=0x7f877dbe55f7 m=0

goroutine 0 [idle]:

goroutine 1 [running, locked to thread]:
runtime.systemstack_switch()
        /usr/lib/golang/src/runtime/asm_amd64.s:216 fp=0xc82004fe90 sp=0xc82004fe88
runtime.newproc(0x0, 0x89d720)
        /usr/lib/golang/src/runtime/proc1.go:2213 +0x62 fp=0xc82004fed8 sp=0xc82004fe90
runtime.init.4()
        /usr/lib/golang/src/runtime/proc.go:141 +0x2b fp=0xc82004fef0 sp=0xc82004fed8
runtime.init()
        /usr/lib/golang/src/runtime/zversion.go:9 +0x378 fp=0xc82004ff50 sp=0xc82004fef0
runtime.main()
        /usr/lib/golang/src/runtime/proc.go:63 +0x103 fp=0xc82004ffa0 sp=0xc82004ff50
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82004ffa8 sp=0xc82004ffa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1696 +0x1
```

---

Reproducing:  I cannot reliably reproduce the problem.  Out of 10 servers it's on, they randomly crash.  

Expected behavior:  Not crashing

Extra info:  I have a single jobber task running every 20 minutes ( 0 */20 \* \* \* \* ) which runs many commands.  The output for those commands would not eat up any memory, maybe 2 megs at the most.  Commands are mostly network related, and then running 2 PHP scripts.

**Comment by Shamunr** [comment]
Happened on another server.  The "Resource unavailable" error is now changed:  

    # jobber list
    runtime/cgo: pthread_create failed: Resource temporarily unavailable
    SIGABRT: abort
    PC=0x7f69b33715f7 m=3
    
    goroutine 0 [idle]:
    
    goroutine 1 [chan receive, locked to thread]:
    text/template/parse.(*Tree).peekNonSpace(0xc820114000, 0x10, 0x30, 0x93c550, 0x1)
            /usr/lib/golang/src/text/template/parse/parse.go:113 +0x169
    text/template/parse.(*Tree).pipeline(0xc820114000, 0x8762a8, 0x5, 0x1)
            /usr/lib/golang/src/text/template/parse/parse.go:388 +0x58
    text/template/parse.(*Tree).parseControl(0xc820114000, 0xc820014100, 0x8762a8, 0x5, 0x0, 0x4, 0x0, 0x0, 0x0)
            /usr/lib/golang/src/text/template/parse/parse.go:455 +0x12c
    text/template/parse.(*Tree).rangeControl(0xc820114000, 0x0, 0x0)
            /usr/lib/golang/src/text/template/parse/parse.go:499 +0x5c
    text/template/parse.(*Tree).action(0xc820114000, 0x0, 0x0)
            /usr/lib/golang/src/text/template/parse/parse.go:373 +0x4fe
    text/template/parse.(*Tree).textOrAction(0xc820114000, 0x0, 0x0)
            /usr/lib/golang/src/text/template/parse/parse.go:350 +0x8d
    text/template/parse.(*Tree).parse(0xc820114000, 0x0, 0x0)
            /usr/lib/golang/src/text/template/parse/parse.go:295 +0x6be
    text/template/parse.(*Tree).Parse(0xc820114000, 0x93c520, 0x172, 0x0, 0x0, 0x0, 0x0, 0xc8200118f0, 0xc82000f320, 0x2, ...)
            /usr/lib/golang/src/text/template/parse/parse.go:234 +0x299
    text/template/parse.Parse(0x87c890, 0x9, 0x93c520, 0x172, 0x0, 0x0, 0x0, 0x0, 0xc82000f320, 0x2, ...)
            /usr/lib/golang/src/text/template/parse/parse.go:55 +0x14c
    text/template.(*Template).Parse(0xc820015480, 0x93c520, 0x172, 0xd0, 0x0, 0x0)
            /usr/lib/golang/src/text/template/template.go:190 +0x2ab
    html/template.(*Template).Parse(0xc8200118c0, 0x93c520, 0x172, 0x0, 0x0, 0x0)
            /usr/lib/golang/src/html/template/template.go:165 +0xb8
    net/rpc.init()
            /usr/lib/golang/src/net/rpc/debug.go:39 +0xf8
    main.init()
            /jobber-1.1/packaging/centos_7/work/BUILD/go_workspace/src/github.com/dshearer/jobber/jobber/jobber.go:299 +0x40
    
    goroutine 17 [syscall, locked to thread]:
    runtime.goexit()
            /usr/lib/golang/src/runtime/asm_amd64.s:1998 +0x1
    
    goroutine 5 [runnable]:
    text/template/parse.lexSpace(0xc820092080, 0x935ed0)
            /usr/lib/golang/src/text/template/parse/lex.go:430 +0xe5
    text/template/parse.(*lexer).run(0xc820092080)
            /usr/lib/golang/src/text/template/parse/lex.go:223 +0x52
    created by text/template/parse.lex
            /usr/lib/golang/src/text/template/parse/lex.go:216 +0x162

**Comment by dshearer** [comment]
Thanks for all the details.  This is strange...  Did you install jobber from the rpm?

**Comment by dshearer** [comment]
This really looks like a problem with your system or with the Go compiler.    I mean "pthread_create failed: Resource temporarily unavailable" just ain't normal.  Have you seen crashes in any other program?

**Comment by dshearer** [comment]
Are you still seeing this?

**Comment by dshearer** [comment]
Closing due to nonresponse.  Please reopen if you want.

**Comment by forsomefun** [comment]
I had the same issue. 
Not sure if you remember, but I removed the task that went on continuously. Now I only have 9 schedules task.  That end within a few moments.

They are basically all Rclones set to move files from a VPS to Google Drive.
I was able to fix the problem by doing the reboot command. Because not even 
jobber reload was working. Kept getting the same error as above.
