### ISSUE TITLE
time config like "0-5" and "10,20" fails

### ISSUE THREAD

**Issue by ironsand** [dshearer/jobber#62]
I got a error when I try to set day of week by `0-5`.

```
Invalid 'weekday' value:strconv.ParseInt: parsing "0-5": invalid syntax
```

And for `sec`, `10,20`

```
Invalid 'sec' value:strconv.ParseInt: parsing "10,20": invalid syntax
```

I checked the source code and found these expression are implemented.
https://github.com/dshearer/jobber/blob/master/jobberd/job_file.go#L480

I have no idea why I got this error. I'm using `CentOS release 6.7 (Final)`.

How can I solve this problem?

Thanks

**Comment by dshearer** [comment]
I'm puzzled.  Could you tell me the full time spec line?

**Comment by ironsand** [comment]
This is a config that causes the error:

```
- name: ExampleJob
  cmd: echo foo
  time: 10,20 0 14 1 8
```

Quoting time like this ` time: "10,20 0 14 1 8"` doesn't help.

And I can add a job by this without error.

```
- name: ExampleJob
  cmd: echo foo
  time: 10 0 14 1 8
```

Any idea?

**Comment by dshearer** [comment]
Ah!  The problem is that I am dumb and didn't notice the obvious --- namely, that support for expressions like "10,20" and "10-20" is not yet in a release.  It's slated for 1.2 (#59 and #65), but I'm not sure when I'll get done with that.

I can make a package from master just for you if you want.

**Comment by ironsand** [comment]
I see, I should have checked out `v1.1`.
I compiled latest master, then the time expression is loaded correctly.

Thanks!
