### ISSUE TITLE
Explanations of error handling are swiched

### ISSUE THREAD

**Issue by ironsand** [dshearer/jobber#63]
I think the explanations of "job error" and "job failure" are switched.

> When discussing jobs, by “job error” we mean the failure of a particular run of a job, whereas by “job failure” we mean a job that jobber has decided not to schedule anymore due to one or more recent job errors.

from [how to use Jobber](http://dshearer.github.io/jobber/doc/v1.1/) 

Thanks

**Comment by dshearer** [comment]
Hm... I don't think so.  What makes you say that?

I really don't like these names: "error" and "failure".  I myself get them confused...

**Comment by ironsand** [comment]
Oh, I see. Sorry it's just my misunderstanding of English.
