### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by sschimmel** [dshearer/jobber#66]
When installing on both OSX and Alpine I get the following error when running `go get github.com/dshearer/jobber`

Error:
`can't load package: package github.com/dshearer/jobber: no buildable Go source files in {GOPATH}/src/github.com/dshearer/jobber`

I'm able to install other packages using go get. 

The contents of `{GOPATH}/src/github.com/dshearer/jobber`:
-rw-r--r--   1 sebastiaan  staff  3732 Nov 11 13:20 DEBIAN_UBUNTU.md
drwxr-xr-x   5 sebastiaan  staff   170 Nov 11 13:20 Godeps
-rw-r--r--   1 sebastiaan  staff  1088 Nov 11 13:20 LICENSE
-rw-r--r--   1 sebastiaan  staff  4725 Nov 11 13:20 Makefile
-rw-r--r--   1 sebastiaan  staff  1476 Nov 11 13:20 README.md
drwxr-xr-x   4 sebastiaan  staff   136 Nov 11 13:20 buildtools
drwxr-xr-x  12 sebastiaan  staff   408 Nov 11 13:20 common
drwxr-xr-x   4 sebastiaan  staff   136 Nov 11 13:20 jobber
drwxr-xr-x  11 sebastiaan  staff   374 Nov 11 13:20 jobberd
drwxr-xr-x   8 sebastiaan  staff   272 Nov 11 13:20 jobfile
drwxr-xr-x   8 sebastiaan  staff   272 Nov 11 13:20 packaging
drwxr-xr-x   9 sebastiaan  staff   306 Nov 11 13:20 platform_tests
-rw-r--r--   1 sebastiaan  staff     4 Nov 11 13:20 version

**Comment by dshearer** [comment]
There are actually multiple libs and programs to build, which are subpackages of github.com/dshearer/jobber.  It would be easier for you to try to use the Makefile.

**Comment by dshearer** [comment]
I'll close this, but please reopen if you're still having trouble.
