### ISSUE TITLE
Does not finish process when running innobackupex command

### ISSUE THREAD

**Issue by josenano** [dshearer/jobber#68]
Hi,

Seems jobber does not finish the process when running a bash script with _innobackupex_ command.
It successfully runs the script but the process runs forever. 

Have to kill jobberd each time. 

Anybody having this issue?

edit: 
Changed the innobackupex command in script with full path seemed to fix the issue. But the backup is not really completed. Some files were missing, and some had 0 size.

Cron runs the same script successfully with no issues.

Thanks,
Jose

**Comment by dshearer** [comment]
Jose,

I haven’t seen that myself.  Could you send the full script?

Dylan

**Comment by josenano** [comment]
Hi Dylan,

The bash script is very simple:
`#!/bin/bash

now=$(date +"%Y-%m-%d_%H-%M")

/usr/bin/innobackupex --compress --no-timestamp --incremental /data/backups/differential-$now --incremental-basedir=/data/backups/full-backup-1
`

Either that script OR the _innobackupex_ command directly in the .jobber config file will cause this issue. The process runs but does not finish at all.

Thanks,
Jose

**Comment by josenano** [comment]
If this helps my jobber version is 1.1

**Comment by dshearer** [comment]
What OS are you using?

**Comment by josenano** [comment]
Yup, I should have added that info too....

It is Ubuntu 14.04.5 LTS

**Comment by dshearer** [comment]
What package provides innobackupex?

**Comment by josenano** [comment]
Is this what you're asking for?

percona-xtrabackup-24 / 2.4.5-1.trusty / amd64

**Comment by dshearer** [comment]
Yes, thanks.

I still haven’t had much time to look into this.  Could you try doing other stuff with jobber to see if the same thing happens?

**Comment by dshearer** [comment]
Are you still having this problem?

**Comment by josenano** [comment]
Hi Dylan,

Is there a new version I can try it out with that fixes this issue? I'm still on 1.1.

**Comment by dshearer** [comment]
Sorry, no.  I will try to recreate this.  Does jobber successfully run any other command on the same system?

**Comment by dshearer** [comment]
I made a VM with Ubuntu 14.04.5 LTS, percona server (MySQL), and percona xtrabackup, and jobber 1.1.  I made a jobber file that calls a script that does this:

`/usr/bin/innobackupex --compress --no-timestamp /data/backups/base`

Everything worked --- jobber was able to run this script.  Of course, I don't have any data in the DB, so there's not much to back up.

Is it possible that, on your system, innobackupex is just taking a very long time?

**Comment by josenano** [comment]
Well for one I also started with a DB with very less data in it. It would only take a few seconds to complete the backup that time.

I'll try it out again. But I have other things running on schedule using jobber on the same server, and there have been no issues.

**Comment by dshearer** [comment]
I want to be sure that I understand the symptoms.  You said that, when Jobber runs innobackupex, the innobackupex command itself completes successfully.  Does that mean that the innobackupex process ends?

**Comment by josenano** [comment]
Hi Dylan, 

> Changed the innobackupex command in script with full path seemed to fix the issue. But the backup is not really completed. Some files were missing, and some had 0 size.

Sorry, I have not had time to re-test. But what I did as described above seemed to fix the issue. I cannot remember correctly now. It has been a few months back. But what I do recall is that the backup result was not as expected. The results are all good when I run it with cron using the same script.

**Comment by dshearer** [comment]
That is strange.  However, I have seen other strange things with how Go does forking, and I'm starting to wonder if they are related.

**Comment by josenano** [comment]
Silly question but may I know when jobber runs the command at the time specified, does it return back or wait for the command's process to finish? I am assuming it will wait.

**Comment by dshearer** [comment]
It waits: each job is run in its own thread, which waits for it to finish.

**Comment by josenano** [comment]
Thanks! 

I'm doing something on another tool (same repos) called `pt-archiver` this week, and preliminary tests looks like it is running okay with jobber. While I'm at it, I can revisit that script I used and do some tests on `innobackupex`.

**Comment by dshearer** [comment]
Closing.  The 1.3 release doesn't do forking, so if you're still having problems please give that a try.
