### ISSUE TITLE
Missing documentation for jobberfile format changes

### ISSUE THREAD

**Issue by henryrizzi** [dshearer/jobber#70]
I was looking through the code trying to get an idea of how to set up email notifications on job failures, but I couldn't really find information about where to set that up.
The docstring for readJobberFile in `jobber/job_file.go` seems to suggest that this would be configured in the jobberfile, but I couldn't find external info in the docs. There seems to only be info about the legacy format.

Is there any other documentation for the new jobberfile format?

**Comment by dshearer** [comment]
The "notify" behavior that the (poorly) named "notifyOnError" and "notifyOnFailure" control does in fact (and always has) send an email.  It uses sendmail, and simply sends it to the user who owns the jobfile.

Unfortunately, you cannot change this behavior in any released version.  However, in version 1.2 there will be a way to specify a custom script to be run.  This code is already in the master branch, but not in any binary packages.

To use this feature, change the jobfile to the new format --- e.g.:
```
[prefs]
notifyProgram: ~/handleError

[jobs]
- name: DailyBackup
  cmd: backup daily
  time: 0 0 14
  onError: Stop
  notifyOnError: false
  notifyOnFailure: true
```

"notifyProgram" should contain a path to the script that should be executed.  It will be run as the user that owns the jobfile (please set the executable bit!).  On stdin, it will be passed a JSON object describing the result of the job run.  You can get an idea of the structure of this JSON here: https://github.com/dshearer/jobber/blob/master/jobfile/run_rec_notifier.go#L43

As I said, this feature isn't in any package, so you'll need to compile from source.  If you want I can easily make a package for you, as long as you're using Debian, RHEL, or Alpine.

**Comment by bgraf-zlab** [comment]
Hey,
thanks for your nice little helper :-). It generally works like a charm so far.
I have a question regarding logging via the notifyProgram though. I tried to set it to `notifyProgram: tee -a /jobber.log` – which in my understanding should basically write (and append) stuff to `/jobber.log`. I quickly checked your code and saw nothing which would prevent this, although I don't know much Go yet. Could you clarify if this could or should work? (`tee` is indeed available in my environment...)
Thanks and best,
Benjamin.

**Comment by dshearer** [comment]
Hi!  No, that won't work.  `notifyProgram` takes a path to a file.  So just make a small shell script that uses `tee`.

**Comment by bgraf-zlab** [comment]
👍 Thanks for clarifying!
