### ISSUE TITLE
Install cannot stat /usr/local/bin/jobber

### ISSUE THREAD

**Issue by trixtur** [dshearer/jobber#72]
I'm compiling from source on openSUSE 13.2, 64 bit version.

The make seems to go smoothly. When I run `make install` I get the following error:

`"install" "/usr/local/bin/jobber" "/usr/local/bin"
install: cannot stat '/usr/local/bin/jobber': No such file or directory
Makefile:80: recipe for target 'install' failed
make: *** [install] Error 1`

I checked and sure enough, the jobber binary wasn't created, even though no error was thrown during compile. I am compiling as root.

The version of Go installed is go-1.4.3-18.1.x86_64

**Comment by trixtur** [comment]
I have manually compiled jobber.go and installed it manually. I am struggling to get jobberd to compile as it is obviously the more complicated of the two.

**Comment by trixtur** [comment]
Ok, I fiddled with the Make file and built each binary individually, then manually placed them into /usr/local/bin.

**Comment by dshearer** [comment]
Would either of the RHEL RPMs work?
