### ISSUE TITLE
Feature: I would like a method for filtering `jobber log`

### ISSUE THREAD

**Issue by trixtur** [dshearer/jobber#74]
I have a task which runs frequently (every few seconds) and I would still like to see the information about the slower running jobs. The issue is that they are being drowned by the spammy tasks.

**Comment by dshearer** [comment]
Is this something that you could use grep for?

**Comment by trixtur** [comment]
It is.

**Comment by dshearer** [comment]
Is grep adequate?

**Comment by trixtur** [comment]
Actually, yes. When I posted this I was thinking more in terms of Jobber doing it for me but I can pipe the output into grep easy enough.
