### ISSUE TITLE
Question: What clears out the runLog buffer?

### ISSUE THREAD

**Issue by trixtur** [dshearer/jobber#75]
I can see this log buffer filling up VERY quickly with jobs running almost every second. Because I'm running jobberd as a daemon, is there something that will clear the log before jobberd crashes and dies in a fire?

Thanks,

-trixtur

**Comment by trixtur** [comment]
This looks like a duplicate of https://github.com/dshearer/jobber/issues/6

**Comment by dshearer** [comment]
Yeah......   This is certainly a bug: the buffer will fill up.

#6 is similar but is a feature request.

**Comment by dshearer** [comment]
PR #100
