### ISSUE TITLE
Support daily, weekly, monthly

### ISSUE THREAD

**Issue by techtonik** [dshearer/jobber#78]
It will be more readable if `jobber` supported human names for `time` field, like `time: daily`.

Like in systemd timers https://jamesbvaughan.github.io/systemd-timers-presentation/#/7

**Comment by trixtur** [comment]
I'm sorry, I have to disagree here. Jobber was written as a replacement for cron and jobber uses cron's time format and adds the ability to run every second if you like. It really isn't that hard to learn.

**Comment by techtonik** [comment]
I was looking for cron replacement too, but not for cron rewrite. So what syntax should I use to ensure that job should be run `daily`, but not on specified time. I don't want all my `daily` scripts suddenly start hammering at 0 hour.

**Comment by techtonik** [comment]
As a `bonus point`, how would I randomize daily times, so that friendly guys who are aware of my jobs won't DDoS my server to make it skip it.

Another `bonus point`. What is the syntax to run the `daily` job anyway for specified day if the day had passed?

**Comment by trixtur** [comment]
You should offset them, The syntax is defined here: http://dshearer.github.io/jobber/doc/v1.1/#time-strings

If you don't want them all to hammer the server at the same time, just offset them with different minutes. I have some jobs that I like to run several times an hour. Knowing that there are 60 minutes in an hour for the minute I just do */6 for the minute part which will run the job 10 times per hour.

Jobber allows you to specify seconds so you could put 0 for one job 10 for another, 20 for another and all 3 jobs will be offset by 10 seconds (if your jobs run quickly) they should be done long before the next job runs.

It really depends on what you mean by "cron rewrite". If you want Jobber to magically go back and run jobs that should have run, jobber isn't for you. Jobber will, however, do something cron won't in that if the job fails it will try again. But you can only define an interval for which jobber should run jobs. Jobber will calculate a future time from the point when it starts to run your jobs.

Jobber is beneficial in that it will rerun your jobs, its job files are defined in a simple to locate file which can be tracked with source control and my personal favorite is that you can't accidentally delete your jobs with a single missed keystroke eg. crontab -e or... oops crontab -r.

Hope this helps.

To run a job on a specified day use:
0,0,0,<day of the month>,*,*

And like I said, if you want to offset your jobs by seconds change the first one to 10 or 20 or whatever. If you want to offset them by minutes change the second, hours 3rd.

**Comment by techtonik** [comment]
> You should offset them, The syntax is defined here: http://dshearer.github.io/jobber/doc/v1.1/#time-strings

There is no word `offset` at that link. Do you mean I should manually adjust time for each job? What advancement in automation over cron is that? =)

I know cron syntax, there is no need to explain it, but thanks anyway. The point is that cron syntax for most simple cases is still unreadable for humans without studying he docs, and I am saying that's not awesome.

> But you can only define an interval for which jobber should run jobs. Jobber will calculate a future time from the point when it starts to run your jobs.

So how do I define a daily interval with random time to start my job? I am fine if Jobber calculates it itself, but what's the syntax?

**Comment by dshearer** [comment]
# Human syntax for time specs

In fact the beta version did use syntax like this.  But, for whatever reasons, I went with cron syntax.

People use Jobber now, so I can't change the syntax w/o killing backward-compatibility.  So I'd have to support two syntaxes.  And right now I'm not sure I want to add that complexity.

For what it's worth, I also often need to look up the order of the fields, so I understand your request.

# Assigning different times to daily jobs

@trixtur is correct: you need to specify a time for each job if you want them to run at different times.

Jobber currently does not support randomizing times.  There was an earlier request for this (#50), so I'll look into it.

**Comment by techtonik** [comment]
> People use Jobber now, so I can't change the syntax w/o killing backward-compatibility. So I'd have to support two syntaxes. And right now I'm not sure I want to add that complexity.
```
if time.startswith('daily'):
   # advanced syntax
else:
   # cron syntax
```

**Comment by trixtur** [comment]
@techtonik I do hope you understood that when I said "offset" I was using the term literally and I meant you would manually offset them by configuring a job to run 10 or 20 seconds after the first.

Your if/else statement is cute. Classic Oversimplification, my clients do this to me all the time. "It should take like 5 minutes right?" The trouble is that the working parts are far more complicated. For sure that will be the 10,000 foot view of the logic but it will definitely not be that easy.

It is open source though so, fork the code and have at it. :-)

**Comment by techtonik** [comment]
> @techtonik I do hope you understood that when I said "offset" I was using the term literally and I meant you would manually offset them by configuring a job to run 10 or 20 seconds after the first.

https://github.com/dshearer/jobber/issues/78#issuecomment-304493375

**Comment by techtonik** [comment]
Now I've got a reason to wait for 1.3 to upgrade. Thanks, @dshearer. =)
