### ISSUE TITLE
jobber -v doesn't work

### ISSUE THREAD

**Issue by techtonik** [dshearer/jobber#82]
```
root@rirror:~# jobber -v

root@rirror:~# jobber -v=true

```
Why?

**Comment by dshearer** [comment]
Bc I suck.

**Comment by techtonik** [comment]
That's a too easy answer. :D

https://github.com/dshearer/jobber/blob/55c6a83a276cf3df663274b2d104c7ef995b97ac/jobber/jobber.go#L63

Somewhere here.

**Comment by techtonik** [comment]
Flags looks okay, so it must be that version strings is not substituted here
https://github.com/dshearer/jobber/blob/master/common/version.go
Which should be done in Makefile
https://github.com/dshearer/jobber/blob/24e9844aceaba7bceff76cf8646ba15350275c42/Makefile#L63

**Comment by techtonik** [comment]
Looks like the problem is with distributive - https://github.com/dshearer/jobber/releases/download/v1.2/jobber_1.2-1_amd64.deb
Because test works ok -
https://travis-ci.org/dshearer/jobber/builds/251868694#L562

Perhaps the problem is here -
https://travis-ci.org/dshearer/jobber/builds/251868694#L3051

**Comment by dshearer** [comment]
Works in master at this time.
