### ISSUE TITLE
Jobber Freezes

### ISSUE THREAD

**Issue by forsomefun** [dshearer/jobber#90]
**1. It there a way to manual look for the jobber log file**
Note: Didn't unrelated but didn't mean to make this text so large, not sure how to change it

My issue is that the program seems to freeze at some points. 
As I was making some changes to the .jobber file. I had to keep uninstalling it and installing the package. 
Because sometimes using the jobber reload command after changing the file would return no results and just hang the program
Jobber log and
Jobber list would also return no results and just hang. 
=====================================================
I'm on ubuntu 16.04
============================================================
Adding this because it is related 

It seems that sometimes even the jobber stop command leads the program to crash on the command line. 

Running the jobber command will still return the list of possible commands. So it seems the program is still running and installed.

**Comment by dshearer** [comment]
This may be caused by #84, which I am actively working on.  Are you running jobs very frequently?

**Comment by forsomefun** [comment]
Not sure what qualifies as frequently
I am running about 5 commands. Every 10 minutes.  
I'm not touching the reload,stop,resume, etc commands on this build because it seems to be causing problems I did */10 so they all start at the same time every 10th minute. 



However, I've been checking the jobber log command, and everyhting seems to be working.

**Comment by dshearer** [comment]
Hm.  Do any of those commands take a while to run?  When 'jobber reload' was hanging for it, it may have been because it was waiting for a command to finish.

To answer your question about the jobber log file (I assume you're asking about the output of 'jobber log'), there is no file that keeps these logs.  I am actually working on changing that right now.

**Comment by forsomefun** [comment]
Maybe that is why

Yes they are programs that are meant to be run 24/7. I'm using jobber and run the programs every 10 minutes. If the command isn't already running.  Then jobber should restart the program. However if the program is already running than jobber will just exit out, and wait for the next 10 minutes.

**Comment by dshearer** [comment]
Ah okay.  Hm.  So you are using jobber to handle crashes of these programs?

**Comment by forsomefun** [comment]
Yes I couldn't figure out cron and this program is setup better in my opinion
I also have this to check if the program is already running
https://apps.ubuntu.com/cat/applications/run-one/

**Comment by dshearer** [comment]
I suspect that Jobber may not be the right tool for you.  It sounds like you'd be better off using Systemd (which I think Ubuntu 16 has).  I am not very familiar with it, but I think you can define each of your programs as a service, and (with "Restart=on-failure" in their service files) Systemd will take care of restarting them if they crash.

**Comment by forsomefun** [comment]
I new to ubuntu/linux so I have not heard of that program.

Looks like it might be good for my uses. I will have to dive in it more.
Thank you

**Comment by dshearer** [comment]
You are very welcome.

**Comment by forsomefun** [comment]
Just wanted to update this for anyone else wbo might have this  problem. 

Hmm didn't realize my continuous scripts were causing the hang up. 
By removing these scripts all previous issues are gone. 

I'm able to reload and everthing
