### ISSUE TITLE
Where is jobber's documentation?

### ISSUE THREAD

**Issue by wonderbeyond** [dshearer/jobber#92]
Is there any or where to find?

- I don't know available cmd options for `jobberd`, or what ENV options may affect its behavior
- Where to place the paths of configuration file
- The format of configuration file (ini or yml)

**Comment by dshearer** [comment]
http://dshearer.github.io/jobber/

**Comment by wonderbeyond** [comment]
That's almost nothing, not a word almost the usage.

I was unable to tweak jobber in docker, then fell back to dcron.

Even no documentation, command options' desc text can help much.

**Comment by dshearer** [comment]
Click “how to use”.  There are many paragraphs.

**Comment by wonderbeyond** [comment]
Sorry, I missed that link(in a plain navbar) and I was trying find a link with text `doc` :sob:
