### ISSUE TITLE
Report error when .jobber is not owned by current user

### ISSUE THREAD

**Issue by techtonik** [dshearer/jobber#93]
Jobber refused to reload jobs one day:
```
# jobber reload -a
Loaded 0 jobs.
```
But the .jobber file is there:
```
# ls -la
total 1652
drwx------  7 root   root      4096 Nov 11 10:18 .
drwxr-xr-x 22 root   root      4096 Apr 12  2017 ..
-rw-------  1 root   root       559 Nov 11 10:48 .bash_history
-rw-r--r--  1 root   root      3106 Oct 22  2015 .bashrc
-rw-rw-r--  1 ubuntu ubuntu     124 Nov 11 11:00 .jobber
```
After changing file ownership to current user, it worked:
```
# chown root:root .jobber 
# jobber reload -a
Loaded 1 jobs.
```

The behaviour is logical, but requires Linux skills. It would be nice if `jobber` could complain before failing. Like:
```
WARN: .jobber file can not be loaded, because it is owned by different user
```
Related to #19.

**Comment by dshearer** [comment]
It'll say something like this:
> Failed to read jobfile /home/vagrant/.jobber: open /home/vagrant/.jobber: permission denied

**Comment by dshearer** [comment]
No PR
