### ISSUE TITLE
Run jobberd under non-root user

### ISSUE THREAD

**Issue by xcrezd** [dshearer/jobber#94]
Hi,

I am trying to run the jobber in docker container which running with non-root user. The .jobber file placed at /home/postgres/.jobber. In my log file i got this:

```
Launching.
Failed to load jobs for open /root/.jobber: permission denied: root
Got jobs section
Failed to load jobs for open /var/spool/exim4/.jobber: permission denied: Debian-exim
totalJobs: -1; len(m.jobs): 1
```

The jobberd process exit with the error. The purpose of using jobber is to replace the crontab, because crontab daemon must be launched under the root user and this is that i want to avoid. 

@dshearer I can make PR with the code like this: If i have at least 1 job(e.g. len(m.jobs): 1 ), the jobberd can proceed normally, no matter if i have "permission denied" for other users.

What you think about it?

**Comment by dshearer** [comment]
Doesn’t it already proceed even if it fails to load other users’ jobs?

**Comment by xcrezd** [comment]
nope, its exits with error code 1

On Wed, Nov 22, 2017 at 11:28 PM, C. Dylan Shearer <notifications@github.com

**Comment by xcrezd** [comment]
After some code debugging, the issue is the socket binding if running jobberd as non-root user account

`
err: listen unix /var/jobber_daemon.sock: bind: permission denied
`

Can we bind it on location that not requiring root permission?

**Comment by dshearer** [comment]
Ah yes...

The perks are set this way for security purposes. You can try changing the owner of that socket to the non-root user. 

FYI I’m working on a new architecture that will make it easier to run it as non-root.

**Comment by dshearer** [comment]
Check out v1.3.0-pr.1.  Follow [these instructions](https://dshearer.github.io/jobber/doc/v1.3/#deployment) to compile it, but then only install jobberrunner and jobber into your container.  You can then run jobberrunner as a daemon as a non-root user.

**Comment by dshearer** [comment]
@xcrezd You may find these Docker images useful: https://hub.docker.com/r/dshearer/jobber/
